name: toxo_sRNA_seq
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11.9
  - trim-galore=0.6.10
  - subread=2.0.6
  - bowtie=1.3.1
  - pandas=2.2.2
  - snakemake=8.13.0
  - samtools=1.22.1
