name: toxo_sRNA_seq
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11.9
  - R-base=4.5.1
  - bioconductor-complexheatmap=2.24.1
  - bioconductor-edger=4.6.3
  - trim-galore=0.6.10
  - subread=2.0.6
  - bowtie=1.3.1
  - pandas=2.2.2
  - snakemake=8.13.0
  - samtools=1.22.1
  - pip
  - pip:
    - pysam=0.23.3
    - tqdm=4.67.1